### PR TITLE
Catch up with upstream

### PR DESCRIPTION
**Pull request by Eijebong**
This re-includes the server side code which is needed to remove `ws` from servo/webrender

### CODE REVIEW

**Comment by jdm** [comment]
```
error[E0425]: cannot find value `FIN` in this scope
   --> src/ws/util/header.rs:136:11
    |
136 |             flags: FIN,
    |                    ^^^ not found in this scope
error[E0425]: cannot find value `FIN` in this scope
   --> src/ws/util/header.rs:146:11
    |
146 |             flags: FIN,
    |                    ^^^ not found in this scope
error[E0425]: cannot find value `RSV1` in this scope
   --> src/ws/util/header.rs:162:11
    |
162 |             flags: RSV1,
    |                    ^^^^ not found in this scope
error[E0425]: cannot find value `RSV1` in this scope
   --> src/ws/util/header.rs:172:11
    |
172 |             flags: RSV1,
    |                    ^^^^ not found in this scope
error[E0425]: cannot find value `RSV1` in this scope
   --> src/ws/util/header.rs:191:11
    |
191 m|             flags: RSV1,
    |                    ^^^^ not found in this scope
```
Also .travis.yml has a use of cargo fmt that isn't working.

**Comment by Eijebong** [comment]
Yep, I'll fix that, didn't thing about testing the nightly feature.
Should we keep the rustfmt part in travis ?

**Comment by jdm** [comment]
I'm not bothered by taking it out.

**Comment by Eijebong** [comment]
Also I want to fix those warnings before it gets merged. (I mostly pushed to try it with servo)

**Comment by Eijebong** [comment]
Everything should be good now :)

**Pull request merged**
